/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class printer_PrinterLibs */

#ifndef _Included_printer_PrinterLibs
#define _Included_printer_PrinterLibs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     printer_PrinterLibs
 * Method:    Port_OpenCom
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_Port_1OpenCom
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_OpenTcp
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_Port_1OpenTcp
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_OpenUsb
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_Port_1OpenUsb
  (JNIEnv *, jclass, jstring);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_OpenLpt
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_Port_1OpenLpt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_Write
 * Signature: ([BCC)I
 */
JNIEXPORT jint JNICALL Java_printer_PrinterLibs_Port_1Write
  (JNIEnv *, jclass, jbyteArray, jchar, jchar);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_Read
 * Signature: ([BCC)I
 */
JNIEXPORT jint JNICALL Java_printer_PrinterLibs_Port_1Read
  (JNIEnv *, jclass, jbyteArray, jchar, jchar);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_printer_PrinterLibs_Port_1Close
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_EnumCom
 * Signature: ([BILprinter/PrinterRefInteger;Lprinter/PrinterRefInteger;)V
 */
JNIEXPORT void JNICALL Java_printer_PrinterLibs_Port_1EnumCom
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jobject);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_EnumLpt
 * Signature: ([BILprinter/PrinterRefInteger;Lprinter/PrinterRefInteger;)V
 */
JNIEXPORT void JNICALL Java_printer_PrinterLibs_Port_1EnumLpt
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jobject);

/*
 * Class:     printer_PrinterLibs
 * Method:    Port_EnumUSB
 * Signature: ([BILprinter/PrinterRefInteger;Lprinter/PrinterRefInteger;)V
 */
JNIEXPORT void JNICALL Java_printer_PrinterLibs_Port_1EnumUSB
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jobject);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_TextOut
 * Signature: (Ljava/lang/String;IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1TextOut
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SetBarcode
 * Signature: (Ljava/lang/String;IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SetBarcode
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SetQRCode
 * Signature: (Ljava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SetQRCode
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_PrintPicture
 * Signature: (Ljava/lang/String;IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1PrintPicture
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SelfTest
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SelfTest
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_FeedLine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1FeedLine
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_FeedNLine
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1FeedNLine
  (JNIEnv *, jclass, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_FeedNDot
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1FeedNDot
  (JNIEnv *, jclass, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_QueryStatus
 * Signature: (ILprinter/PrinterRefLong;C)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1QueryStatus
  (JNIEnv *, jclass, jint, jobject, jchar);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_RTQueryStatus
 * Signature: (ILprinter/PrinterRefInteger;C)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1RTQueryStatus
  (JNIEnv *, jclass, jint, jobject, jchar);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_TicketSucceed
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1TicketSucceed
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SetMotionUnit
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SetMotionUnit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SetLineHeight
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SetLineHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_SetRightSpacing
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1SetRightSpacing
  (JNIEnv *, jclass, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_Reset
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1Reset
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_KickOutDrawer
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1KickOutDrawer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_FeedAndCutPaper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1FeedAndCutPaper
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_FullCutPaper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1FullCutPaper
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_HalfCutPaper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1HalfCutPaper
  (JNIEnv *, jclass);

/*
 * Class:     printer_PrinterLibs
 * Method:    POS_Beep
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_printer_PrinterLibs_POS_1Beep
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
